### ISSUE TITLE
Authorization flow with AD groups

### ISSUE THREAD

**Issue by azaborovskyi** [jkroepke/openvpn-auth-azure-ad#10]
Hello, tell me please, if it is possible to configure this service for user authorization from a specific AD group?

**Comment by jkroepke** [comment]
As I know, you can restrict them on AD site.

https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users

**Comment by azaborovskyi** [comment]
Ok, thank you I try it.
Tell me which client to use for Windows to support device authorization flow?

**Comment by jkroepke** [comment]
I recently tested the OpenVPN Client for Windows. https://openvpn.net/community-downloads/
