### ISSUE TITLE
Frequent disconnections from the OpenVPN server

### ISSUE THREAD

**Issue by azaborovskyi** [jkroepke/openvpn-auth-azure-ad#15]
Hello, I configured OpenVPN server with device auth flow from Azure AD and  I'm faced with the problem of often disconnection from my OpenVPN server, I do not observe any problems with the network, not found any criticals error/ warnings in the OpenVPN server logs. But in the logs of the "openvpn-auth-azure-ad" service, at the time of the disconnect, there is a message "Received client re auth event". Can you tell me which way to look?

**Comment by azaborovskyi** [comment]
no one can tell? maybe met with this?

**Comment by jkroepke** [comment]
without any OpenVPN logs, it could be anything.

By default, there is a feature in OpenVPN enabled which renegotiate the channel each hour. This will introduce a reconnect on client or server side.

This feature is not related to this project. Maybe the option helps you`reneg-sec` to find more information about this.

**Comment by azaborovskyi** [comment]
Ok, thank you I will try add reneg-sec option and test it, if it not resolve the problem, I'll attached logs

**Comment by azaborovskyi** [comment]
Configuring "reneg-sec" resolved my problem, thanks.
