### ISSUE TITLE
Version issues

### ISSUE THREAD

**Issue by LBegnaud** [jkroepke/openvpn-auth-azure-ad#18]
the `latest` tag in docker hub is 7months old, and the `main` tag seems to have an error :(

![image](https://user-images.githubusercontent.com/15981748/201745662-9599f339-ca55-4472-a56f-14d2e888b058.png)

**Comment by jkroepke** [comment]
Hi @MowFord,

thanks for the report. I fixed the issue and released a new version.

**Comment by LBegnaud** [comment]
Thanks!
