### ISSUE TITLE
Stuck on "PUSH REQUEST"

### ISSUE THREAD

**Issue by LoRKaa** [jkroepke/openvpn-auth-azure-ad#21]
My openvpn.log

WR2022-11-29 17:32:02 us=372844 xxxxxxxxxxxxxx:63767 PUSH: Received control message: 'PUSH_REQUEST'
WR2022-11-29 17:32:07 us=643615 xxxxxxxxxxxxxx:63767 PUSH: Received control message: 'PUSH_REQUEST'
WR2022-11-29 17:32:12 us=910058 xxxxxxxxxxxxxx:63767 PUSH: Received control message: 'PUSH_REQUEST'
WR2022-11-29 17:32:18 us=186870 xxxxxxxxxxxxxx:63767 PUSH: Received control message: 'PUSH_REQUEST'
WR2022-11-29 17:32:23 us=268419 xxxxxxxxxxxxxx:63767 PUSH: Received control message: 'PUSH_REQUEST'
WR2022-11-29 17:32:27 us=338487 xxxxxxxxxxxxxx:63767 PUSH: Received control message: 'PUSH_REQUEST'
WR2022-11-29 17:32:32 us=498104 xxxxxxxxxxxxxx:63767 PUSH: Received control message: 'PUSH_REQUEST'

No ending connection

**Comment by jkroepke** [comment]
And logs from openvpn-auth-azure-ad?

**Comment by LoRKaa** [comment]
SOLVED

had the wrong endpoint, works fine, thanks for your work
